class AppStrings {
  static const Map<String, Map<String, String>> _localized = {
    'EN': {
      'title': 'Exchange Rates',
      'search_hint': 'Search currencies...',
      'loading': 'Loading exchange rates...',
      'error_title': 'Oops! Something went wrong',
      'retry': 'Try Again',
      'no_results': 'No currencies found',
      'try_other': 'Try a different search term',
      'popular': 'Popular',
      'trending': 'Trending',
      'all': 'All',
      'convert': 'Convert',
      'rate': 'Rate',
      'select_language': 'Select Language',
      'sort_by': 'Sort By',
      'name': 'Name (A-Z)',
      'most_popular': 'Most Popular',
      'highest_rate': 'Highest Rate',
      'english': 'English',
      'uzbek': 'Uzbek',
      'russian': 'Russian',
      'analytics': 'Analytics',
      'current_rate': 'Current Rate',
      'statistics': 'Statistics',
      'high': 'High',
      'low': 'Low',
      'average': 'Average',
      'volatility': 'Volatility',
      'market_insights': 'Market Insights',
      'bullish_title': 'Bullish Trend',
      'bullish_desc': 'Currency is strengthening',
      'bearish_title': 'Bearish Trend',
      'bearish_desc': 'Currency is weakening',
      'stability_title': 'Stability',
      'stability_desc': 'Currency remains relatively stable',

    },

    'UZ': {
      'title': 'Valyuta kurslari',
      'search_hint': 'Valyutani qidiring...',
      'loading': 'Valyuta kurslari yuklanmoqda...',
      'error_title': 'Xatolik yuz berdi',
      'retry': 'Qayta urinish',
      'no_results': 'Valyuta topilmadi',
      'try_other': 'Boshqa so‘z kiriting',
      'popular': 'Ommabop',
      'trending': 'O‘sishda',
      'all': 'Barchasi',
      'convert': 'Konvertatsiya',
      'rate': 'Kurs',
      'select_language': 'Tilni tanlang',
      'sort_by': 'Saralash',
      'name': 'Nomi (A–Z)',
      'most_popular': 'Eng ommabop',
      'highest_rate': 'Eng yuqori kurs',
      'analytics': 'Tahlili',
      'current_rate': 'Joriy kurs',
      'statistics': 'Statistika',
      'high': 'Yuqori',
      'low': 'Past',
      'average': 'O‘rtacha',
      'volatility': 'O‘zgaruvchanlik',
      'market_insights': 'Bozor tahlili',
      'bullish_title': 'O‘sish tendensiyasi',
      'bullish_desc': 'Valyuta kuchi ortib bormoqda',
      'bearish_title': 'Pasayish tendensiyasi',
      'bearish_desc': 'Valyuta kuchi kamaymoqda',
      'stability_title': 'Barqarorlik',
      'stability_desc': 'Valyuta nisbatan barqaror',
    },

    'RU': {
      'title': 'Курсы валют',
      'search_hint': 'Поиск валют...',
      'loading': 'Загрузка курсов валют...',
      'error_title': 'Что-то пошло не так',
      'retry': 'Повторить',
      'no_results': 'Валюты не найдены',
      'try_other': 'Попробуйте другой запрос',
      'popular': 'Популярные',
      'trending': 'В тренде',
      'all': 'Все',
      'convert': 'Конвертировать',
      'rate': 'Курс',
      'select_language': 'Выберите язык',
      'sort_by': 'Сортировать',
      'name': 'Название (A–Z)',
      'most_popular': 'Самые популярные',
      'highest_rate': 'Самый высокий курс',
      'analytics': 'Аналитика',
      'current_rate': 'Текущий курс',
      'statistics': 'Статистика',
      'high': 'Макс.',
      'low': 'Мин.',
      'average': 'Средний',
      'volatility': 'Волатильность',
      'market_insights': 'Обзор рынка',
      'bullish_title': 'Бычий тренд',
      'bullish_desc': 'Валюта укрепляется',
      'bearish_title': 'Медвежий тренд',
      'bearish_desc': 'Валюта ослабевает',
      'stability_title': 'Стабильность',
      'stability_desc': 'Валюта относительно стабильна',
    },
  };

  static String t(String key, String lang) {
    return _localized[lang]?[key] ?? _localized['EN']![key] ?? key;
  }
}
